### ISSUE TITLE
Could not compile `maidsafe_vault`.

### ISSUE THREAD

**Issue by southsideGLA** [maidsafe/maidsafe_vault#127]
Latest updates of everything - inc rust nightly    Ubuntu 15.-4 64bit

willie@gagarin:~/projects/MaidSafe/maidsafe_vault$ cargo build --verbose
       Fresh gcc v0.3.8
       Fresh term v0.2.9
       Fresh byteorder v0.3.10
       Fresh regex-syntax v0.1.2
       Fresh rustc-serialize v0.3.15
       Fresh libc v0.1.8
       Fresh itertools v0.3.19
       Fresh strsim v0.3.0
       Fresh cbor v0.3.7
       Fresh libsodium-sys v0.0.5
       Fresh rand v0.3.8
       Fresh num_cpus v0.2.6
       Fresh memchr v0.1.3
       Fresh log v0.3.1
       Fresh sodiumoxide v0.0.5
       Fresh num v0.1.25
       Fresh asynchronous v0.4.5
       Fresh aho-corasick v0.2.1
       Fresh time v0.1.26
       Fresh regex v0.1.38
       Fresh message_filter v0.1.1
       Fresh lru_time_cache v0.1.8
       Fresh docopt v0.6.67
       Fresh env_logger v0.3.1
       Fresh accumulator v0.0.1
       Fresh utp v0.6.0
       Fresh crust v0.1.3
       Fresh routing v0.2.6
   Compiling maidsafe_vault v0.1.0 (file:///home/willie/projects/MaidSafe/maidsafe_vault)
     Running `rustc src/main.rs --crate-name maidsafe_vault --crate-type bin -g --out-dir /home/willie/projects/MaidSafe/maidsafe_vault/target/debug --emit=dep-info,link -L dependency=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug -L dependency=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps --extern maidsafe_types=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libmaidsafe_types-e022f498f2e0be44.rlib --extern crust=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libcrust-1a311ed8aa8931d9.rlib --extern rustc_serialize=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/librustc_serialize-c1e8163a38ed3d54.rlib --extern cbor=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libcbor-0bd941ffbb5daf77.rlib --extern routing=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/librouting-438939270f2da06f.rlib --extern sodiumoxide=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libsodiumoxide-75eb99c13a8dec07.rlib --extern lru_time_cache=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/liblru_time_cache-7fa82329a30ad63b.rlib --extern time=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libtime-10c3f659b0cce9f1.rlib --extern docopt=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libdocopt-141ed6b1383f3228.rlib -L native=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/build/time-10c3f659b0cce9f1/out`
       Fresh maidsafe_types v0.2.2
src/pmid_manager/database.rs:25:22: 25:29 error: unresolved import `maidsafe_types::Payload`. There is no `Payload` in `maidsafe_types`
src/pmid_manager/database.rs:25 use maidsafe_types::{Payload, PayloadTypeTag};
                                                     ^~~~~~~
src/pmid_manager/database.rs:25:31: 25:45 error: unresolved import `maidsafe_types::PayloadTypeTag`. There is no `PayloadTypeTag` in `maidsafe_types`
src/pmid_manager/database.rs:25 use maidsafe_types::{Payload, PayloadTypeTag};
                                                              ^~~~~~~~~~~~~~
src/maid_manager/database.rs:25:22: 25:29 error: unresolved import `maidsafe_types::Payload`. There is no `Payload` in `maidsafe_types`
src/maid_manager/database.rs:25 use maidsafe_types::{Payload, PayloadTypeTag};
                                                     ^~~~~~~
src/maid_manager/database.rs:25:31: 25:45 error: unresolved import `maidsafe_types::PayloadTypeTag`. There is no `PayloadTypeTag` in `maidsafe_types`
src/maid_manager/database.rs:25 use maidsafe_types::{Payload, PayloadTypeTag};
                                                              ^~~~~~~~~~~~~~
src/data_manager/database.rs:20:22: 20:29 error: unresolved import `maidsafe_types::Payload`. There is no `Payload` in `maidsafe_types`
src/data_manager/database.rs:20 use maidsafe_types::{Payload, PayloadTypeTag};
                                                     ^~~~~~~
src/data_manager/database.rs:20:31: 20:45 error: unresolved import `maidsafe_types::PayloadTypeTag`. There is no `PayloadTypeTag` in `maidsafe_types`
src/data_manager/database.rs:20 use maidsafe_types::{Payload, PayloadTypeTag};
                                                              ^~~~~~~~~~~~~~
error: aborting due to 6 previous errors
Could not compile `maidsafe_vault`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name maidsafe_vault --crate-type bin -g --out-dir /home/willie/projects/MaidSafe/maidsafe_vault/target/debug --emit=dep-info,link -L dependency=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug -L dependency=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps --extern maidsafe_types=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libmaidsafe_types-e022f498f2e0be44.rlib --extern crust=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libcrust-1a311ed8aa8931d9.rlib --extern rustc_serialize=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/librustc_serialize-c1e8163a38ed3d54.rlib --extern cbor=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libcbor-0bd941ffbb5daf77.rlib --extern routing=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/librouting-438939270f2da06f.rlib --extern sodiumoxide=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libsodiumoxide-75eb99c13a8dec07.rlib --extern lru_time_cache=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/liblru_time_cache-7fa82329a30ad63b.rlib --extern time=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libtime-10c3f659b0cce9f1.rlib --extern docopt=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/deps/libdocopt-141ed6b1383f3228.rlib -L native=/home/willie/projects/MaidSafe/maidsafe_vault/target/debug/build/time-10c3f659b0cce9f1/out` (exit code: 101)
willie@gagarin:~/projects/MaidSafe/maidsafe_vault$ 

Just to confirm I updated maidsafe_types and  cargo test -- release --verbose passed OK

**Comment by maqi** [comment]
there is ongoing work of removing Payload, and here is the PR : 
https://github.com/maidsafe/maidsafe_vault/pull/128
