### ISSUE TITLE
Changing number of vaults results in "Failed :: Network IO Error"

### ISSUE THREAD

**Issue by maveric** [maidsafe/maidsafe_vault#130]
Adding or removing a vault is not handled properly as far as I can tell. The vault prints out "Handle CHURN new node 79fda8..e631e5" but does not seem to handle it properly. The results are the same for going from 4 to 3 vaults, that output is not shown.

From my understanding, adding a vault should change nothing unless another vault drops off line or new data is added, neither of these are true in the below outputs.

If this is an issue with how client handles something please let me know and I'll move it.

Layout of below text:
first output: maidsafe_client frontending the vault setup. Backended was 3 vaults, with a 4'th added  as noted in the output.
second output: Last added vault (#4)
third output: First seed vault

root@kali:/MaidSafe/maidsafe_client# echo "3 vaults currently running"
3 vaults currently running
root@kali:/MaidSafe/maidsafe_client# cargo run --example rest_api --features "USE_ACTUAL_ROUTING"
     Running `target/debug/examples/rest_api`

	Account Creation
	================

------------ Enter Keyword ---------------
test

------------ Enter Password --------------
test

--------- Enter PIN (4 Digits) -----------
1234

Trying to create an account ...
trying to bootstrapped client
bootstrapped client
Sending connect request
received a ConnectResponse from Tcp(V4(127.0.0.1:46708))
Put sent out with message_id 1223226955
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Put sent out with message_id 1223226956
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Account Created Successfully !!
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))

	Auto Account Login
	==================

Trying to log into the created account using supplied credentials ...
trying to bootstrapped client
bootstrapped client
Sending connect request
received a ConnectResponse from Tcp(V4(127.0.0.1:46708))
Get sent out with message_id 1749025711
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
Get sent out with message_id 1749025712
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
trying to bootstrapped client
Account Login Successful !!

	-- Preparing storage ----

bootstrapped client
Sending connect request
Put sent out with message_id 916441461
received a ConnectResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Put sent out with message_id 916441462
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Put sent out with message_id 916441463
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Get sent out with message_id 916441464
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
Put sent out with message_id 916441465
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Get sent out with message_id 916441466
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
Get sent out with message_id 916441467
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))

------  (Tip) Start by creating a container and then store blob, modify blob within the container --------------------

----------Choose an Operation----------------
1. Create Container
2. List Containers
3. Get Root Container Versions
4. Delete Container
5. List Blobs from container
6. Create Blob
7. Update Blob
8. Get blob content
9. Get blob content by version
10. Delete blob
11. Copy blob
------ Enter a number --------------------
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
1

------Enter Container name--------
container1
Put sent out with message_id 916441468
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Put sent out with message_id 916441469
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Get sent out with message_id 916441470
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
Get sent out with message_id 916441471
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
Get sent out with message_id 916441472
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
Put sent out with message_id 916441473
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Put sent out with message_id 916441474
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
Created Container - container1

----------Choose an Operation----------------
1. Create Container
2. List Containers
3. Get Root Container Versions
4. Delete Container
5. List Blobs from container
6. Create Blob
7. Update Blob
8. Get blob content
9. Get blob content by version
10. Delete blob
11. Copy blob
------ Enter a number --------------------
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
received a PutDataResponse from Tcp(V4(127.0.0.1:46708))
2

List of containers
	        Created On                  Name 
	 =========================       ==========
	 "27-06-2015 23:23 UTC" 	 container1

----------Choose an Operation----------------
1. Create Container
2. List Containers
3. Get Root Container Versions
4. Delete Container
5. List Blobs from container
6. Create Blob
7. Update Blob
8. Get blob content
9. Get blob content by version
10. Delete blob
11. Copy blob
------ Enter a number --------------------
5

------Enter Container name--------
container1
Get sent out with message_id 916441475
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
No Blobs found in Container - container1

----------Choose an Operation----------------
1. Create Container
2. List Containers
3. Get Root Container Versions
4. Delete Container
5. List Blobs from container
6. Create Blob
7. Update Blob
8. Get blob content
9. Get blob content by version
10. Delete blob
11. Copy blob
------ Enter a number --------------------
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
adding another vault

Enter a valid number

----------Choose an Operation----------------
1. Create Container
2. List Containers
3. Get Root Container Versions
4. Delete Container
5. List Blobs from container
6. Create Blob
7. Update Blob
8. Get blob content
9. Get blob content by version
10. Delete blob
11. Copy blob
------ Enter a number --------------------
5

------Enter Container name--------
container1
Get sent out with message_id 916441476
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
Failed :: Network IO Error

----------Choose an Operation----------------
1. Create Container
2. List Containers
3. Get Root Container Versions
4. Delete Container
5. List Blobs from container
6. Create Blob
7. Update Blob
8. Get blob content
9. Get blob content by version
10. Delete blob
11. Copy blob
------ Enter a number --------------------
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
received a GetDataResponse from Tcp(V4(127.0.0.1:46708))
2

List of containers
	        Created On                  Name 
	 =========================       ==========
	 "27-06-2015 23:23 UTC" 	 container1

----------Choose an Operation----------------
1. Create Container
2. List Containers
3. Get Root Container Versions
4. Delete Container
5. List Blobs from container
6. Create Blob
7. Update Blob
8. Get blob content
9. Get blob content by version
10. Delete blob
11. Copy blob
------ Enter a number -------------------

-----------------------------------------------------------------------------------------------------------------------------

Output from last added vault:

root@kali:/MaidSafe/maidsafe_vault# cargo run --release
     Running `target/release/maidsafe_vault`
BOOTSTRAP to Tcp(V4(192.168.1.142:39176))
NODE listening on Some(Tcp(V4(127.0.0.1:52973)))
Waiting for responses from network
NewConnection on Tcp(V4(127.0.0.1:39176)) while waiting on network.
NewConnection on Tcp(V4(127.0.0.1:53515)) while waiting on network.
NewConnection on Tcp(V4(192.168.1.142:39176)) while waiting on network.
NewConnection on Tcp(V4(127.0.0.1:46708)) while waiting on network.
Received connect response
Received PutPublicId relocated name Some(79fda8..e631e5) from 1782c4..8084ed
Started Membrane loop
CRUST::NewConnection on Tcp(V4(127.0.0.1:47822))
RT (size : 1) added connected node 611033..190c70 on Tcp(V4(127.0.0.1:47822))
Handle CHURN new node 611033..190c70
CRUST::NewConnection on Tcp(V4(127.0.0.1:47823))
RT (size : 2) added connected node 60ef63..546c38 on Tcp(V4(127.0.0.1:47823))
Handle CHURN new node 60ef63..546c38
CRUST::NewConnection on Tcp(V4(127.0.0.1:47824))
RT (size : 3) added connected node b624ad..a51511 on Tcp(V4(127.0.0.1:47824))
Handle CHURN new node b624ad..a51511

-----------------------------------------------------------------------------------------------------------

output from first vault:

root@kali:/MaidSafe/maidsafe_vault# cargo run --release -- --first
     Running `target/release/maidsafe_vault --first`
ZERO listening on Some(Tcp(V4(127.0.0.1:39176))), named 611033..190c70
Started Membrane loop
CRUST::NewConnection on Tcp(V4(127.0.0.1:43349))
CRUST::NewConnection on Tcp(V4(192.168.1.142:45331))
Added endpoint Tcp(V4(192.168.1.142:45331)) to relay map, named 2d8c05..6c3d6b
FIRST NODE BOOSTRAPS OFF OF ZERO NODE
CRUST::NewConnection on Tcp(V4(127.0.0.1:53515))
RT (size : 1) added connected node 60ef63..546c38 on Tcp(V4(127.0.0.1:53515))
Handle CHURN new node 60ef63..546c38
CRUST::NewConnection on Tcp(V4(192.168.1.142:45337))
CRUST::NewConnection on Tcp(V4(127.0.0.1:43354))
Added endpoint Tcp(V4(192.168.1.142:45337)) to relay map, named cb11ff..0ee594
CRUST::NewConnection on Tcp(V4(127.0.0.1:46708))
RT (size : 2) added connected node b624ad..a51511 on Tcp(V4(127.0.0.1:46708))
Handle CHURN new node b624ad..a51511
CRUST::NewConnection on Tcp(V4(127.0.0.1:43361))
CRUST::NewConnection on Tcp(V4(192.168.1.142:45346))
Handle PUT data response.
Handle PUT data response.
CRUST::NewConnection on Tcp(V4(127.0.0.1:43368))
CRUST::NewConnection on Tcp(V4(192.168.1.142:45353))
Reply GetData to b624ad..a51511 with relay Some(062b14..e520e1) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(062b14..e520e1) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(062b14..e520e1) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(062b14..e520e1) on node 611033..190c70.
CRUST::NewConnection on Tcp(V4(192.168.1.142:45359))
CRUST::NewConnection on Tcp(V4(127.0.0.1:43375))
Handle PUT data response.
Handle PUT data response.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Handle PUT data response.
Handle PUT data response.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Handle PUT data response.
Handle PUT data response.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
Handle PUT data response.
Handle PUT data response.
Reply GetData to b624ad..a51511 with relay Some(d6a84d..ab8edb) on node 611033..190c70.
CRUST::NewConnection on Tcp(V4(127.0.0.1:43381))
CRUST::NewConnection on Tcp(V4(192.168.1.142:45363))
Added endpoint Tcp(V4(192.168.1.142:45363)) to relay map, named 1782c4..8084ed
CRUST::NewConnection on Tcp(V4(127.0.0.1:52973))
RT (size : 3) added connected node 79fda8..e631e5 on Tcp(V4(127.0.0.1:52973))
Handle CHURN new node 79fda8..e631e5

**Comment by dirvine** [comment]
On Sun, Jun 28, 2015 at 12:53 AM, maveric <notifications@github.com> wrote:

> From my understanding, adding a vault should change nothing unless another
> vault drops off line or new data is added, neither of these are true in the
> below outputs.


I think this is due to the fact your network is less than QUORUM size so
every add/remove will or should show churn happening.


-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by maveric** [comment]
Even if the churn does happen every time because of the low size, after it happens I should still be able to see the contents of a container after adding a vault redardless, no?

**Comment by dirvine** [comment]
On Sun, Jun 28, 2015 at 1:24 AM, maveric <notifications@github.com> wrote:

> no?


Yes it should, when the network is small there are edge effects though. It
should show churn and you should see the same content. Good you are testing
this we have not had the time to test churn yet (only got the network
working and posted a way to play around). So this is basically virgin
territory, there are a few updates that you wont have that are churn
related. If you were very keen you could change the cargo,toml to use the
routing git repo instead of crates to see if that makes any difference.

I only recently came across the sentences that end in yes? or no?, it's
weird for us Scottish folk to see that, feels like you are stating what the
answer is rather than asking a question.  It is asking a question though I
am sure, well not 100% so. Anyway I have answered this as though it was a
question :-)

Thanks for the testing, great to get feedback, makes our job so much
simpler. Let me know if you use teh Routing git repo direct. I know Ben was
doing a good bit of work there yesterday.


-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by maveric** [comment]
I was editing the question to change the tone to not sound so much like a jab, apparently as you were answering it. I tried to be quick about it, but apparently you're much quicker.

As for the ending "no?/yes?": Here in the U.S. its generally used to state your assumption and ask for confirmation. However it's got a pretty "nose in the air" connotation, hence me trying to change it before you got to it.

All that to say; thank you for answering my question. I debated even raising an issue as I know its still WIP, but figured too much info is better than not enough.

**Comment by dirvine** [comment]
On Sun, Jun 28, 2015 at 1:45 AM, maveric <notifications@github.com> wrote:

> All that to say; thank you for answering my question. I debated even
> raising an issue as I know its still WIP, but figured too much info is
> better than not enough.


Not al all every single bit of feedback is really cool and does help a lot.
Don't worry about tone, it's just a new thing I see nowadays. I thought it
was a USA thing, which is fine if that's the culture, not a concern at all.
Thanks again


-- 

David Irvine
twitter: @metaquestions
blog:  http://metaquestions.me

**Comment by maqi** [comment]
resolving in https://github.com/maidsafe/maidsafe_vault/pull/148
