### ISSUE TITLE
No new vaults after first client.  

### ISSUE THREAD

**Issue by bobberb** [maidsafe/maidsafe_vault#135]
To reproduce (Digital Ocean Droplet Ubuntu 14.04, libsodium built from source, rest from cargo builds) :

Start up

>cargo run --release -- --first

then create as many 

>cargo run --release 

vaults as desired.  Create client with

>cargo run --example self_authentication --features "USE_ACTUAL_ROUTING"

Create container, blob, Ctrl-C to quit.

Opening any new vault with crash the whole network.  Any new clients will hang until the series has been reset.  

> root@aizu:~/maidsafe_vault# cargo run --release
     Running `target/release/maidsafe_vault`
BOOTSTRAP to Tcp(V4(127.0.0.1:55717))
NODE listening on Some(Tcp(V4(127.0.0.1:40743)))
Waiting for responses from network
NewConnection on Tcp(V4(127.0.0.1:37654)) while waiting on network.
NewConnection on Tcp(V4(45.55.236.243:37654)) while waiting on network.
NewConnection on Tcp(V4(172.17.42.1:37654)) while waiting on network.
NewConnection on Tcp(V4(127.0.0.1:48338)) while waiting on network.
NewConnection on Tcp(V4(127.0.0.1:33945)) while waiting on network.
NewConnection on Tcp(V4(127.0.0.1:55717)) while waiting on network.
NewConnection on Tcp(V4(127.0.0.1:42244)) while waiting on network.
Received connect response
Received PutPublicId relocated name Some(5ca971..6abc89) from 055307..d1e984
Started Membrane loop
REFLECT OUR GROUP
CRUST::NewConnection on Tcp(V4(127.0.0.1:48550))
CRUST::NewConnection on Tcp(V4(127.0.0.1:48551))
CRUST::NewConnection on Tcp(V4(127.0.0.1:48552))
CRUST::NewConnection on Tcp(V4(127.0.0.1:48553))
CRUST::NewConnection on Tcp(V4(127.0.0.1:48554))
RT (size : 1) added connected node a362aa..8c92b1 on Tcp(V4(127.0.0.1:48550))
Handle CHURN new node a362aa..8c92b1
RT (size : 2) added connected node 937ee9..7d5028 on Tcp(V4(127.0.0.1:48551))
Handle CHURN new node 937ee9..7d5028
RT (size : 3) added connected node e4534f..281eec on Tcp(V4(127.0.0.1:48552))
Handle CHURN new node e4534f..281eec
RT (size : 4) added connected node cc9a47..c10b51 on Tcp(V4(127.0.0.1:48553))
Handle CHURN new node cc9a47..c10b51
RT (size : 5) added connected node 78add8..d67116 on Tcp(V4(127.0.0.1:48554))
Handle CHURN new node 78add8..d67116
thread '<unnamed>' panicked at 'assertion failed: data_stored.len() < (GROUP_SIZE + 1) / 2', src/maid_manager/database.rs:90

**Comment by maqi** [comment]
This is another scenario exposing the churn handling issue as reported in Issue https://github.com/maidsafe/maidsafe_vault/issues/130

**Comment by maqi** [comment]
resolving in https://github.com/maidsafe/maidsafe_vault/pull/148
