### ISSUE TITLE
Error stopping vault when client is connected

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/maidsafe_vault#137]
Testing environment : 5 x Ubuntu 15.04 / rustc 1.3.0-nightly (bf3c979ec 2015-06-30)
1 machine running maidsafe_client (debug) `rest_api` / 4 x vault machines (debug) on a LAN. 

When you stop a `vault` with `maidsafe_client` connected you get the error below this is not the case in a pure vault network with no clients connected. 

```
RT (size : 2) connection Tcp(V4(192.168.1.70:53333)) disconnected for 8d06c6..e4048f.
Handle CHURN lost node
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Decode(TypeMismatch { expected: Array, got: UInt64 })', ../src/libcore/result.rs:731
```

**Comment by maqi** [comment]
This is also another scenario exposing possible bugs in churn handling.
The issue will be covered in the task https://maidsafe.atlassian.net/browse/MAID-1017

**Comment by maqi** [comment]
resolving in https://github.com/maidsafe/maidsafe_vault/pull/148
