### ISSUE TITLE
OS X : test::executable_test ... FAILED

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/maidsafe_vault#92]
```
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D136
rustc 1.2.0-nightly (613e57b44 2015-06-01) (built 2015-06-01)
```

CI Failure and confirmed manually - **OS X test failure** - I can confirm that no other examples are  running on the same machine at the same time and ` RUST_TEST_THREADS=1 `  is being used
```
failures:

---- test::executable_test stdout ----
	---------- starting node 0 --------------
thread 'test::executable_test' panicked at 'couldn't spawn maidsafe_vault: os error', src/main.rs:130



failures:
    test::executable_test

test result: FAILED. 29 passed; 1 failed; 0 ignored; 0 measured

thread '<main>' panicked at 'Some tests failed', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libtest/lib.rs:255
```

**Comment by maqi** [comment]
looks like the maidsafe_vault is not available at the expected location.
could you please do a manual check whether the executable is available?
thx

**Comment by rossmuir** [comment]
You are correct Qi `maidsafe_vault` did not get built - I followed the same steps on another Mac and everything worked fine - I will investigate further.

**Comment by maqi** [comment]
shall I close this issue ?
