### ISSUE TITLE
Account Transfer: orderable records only

### ISSUE THREAD

**Issue by benjaminbollen** [maidsafe/maidsafe_vault#96]
routing Sendable trait has a function merge that is currently used by the Vaults implementation.

Current routing does not, and does not in a nearby release plan to call .merge; code in this trait will be effectively dead code.

Routing has for account transfer a Sentinel that specifically can accumulate messages that have an orderable value. MAID-1068 should have been handled earlier and gives a specific Refresh message type that Vaults can template with their own account_transfer type.  (only one type that needs to hold any different record types though). The (templated) Value of this AccountTransfer message needs to be orderable.
https://maidsafe.atlassian.net/browse/MAID-1068

The concern has been raised that DataManager holds a non-orderable record type.  Consider the following proposal; DM records hold the PMIDnodes that store a given chunk:
chunk1   ->    vec![nodeA, nodeB, nodeC]
chunk2   ->    vec![nodeA, nodeF, nodeH]

as a vector it is not orderable;  vault code could simplify however if DM (holds the records as following), sends out records to the network as following:

(chunk1, nodeA)   ->  "primary copy"
(chunk1, nodeB)   ->  "primary copy"
(chunk1, nodeC)   ->  "backup copy"
(chunk2, nodeA)    ->  "primary copy"
(chunk2, nodeF)    ->  "primary copy"
(chunk2, nodeH)   ->   "backup copy"

for sure something smarter can be done with "primary copy"; that just an example.  This approach however, relies on the network and account Sentinel to 'refresh' the records of DM on churn.  It abuses the orderable value (in the example "primary", "backup", these are orderable); but more importantly; they should be identical for a majority of group members.  Then Sentinel can resolve on this record by accumulating the (chunk, node) records, and if a quorum (signed) agrees, then that is a new record after refresh.

**Comment by maqi** [comment]
Vault is not using "merge" trait, Vault just implement that trait which supposed to be used by Routing instead.

On DM, Primary/Backup/Sacrificial copies are stored seperately.
i.e. chunk1 is just a Primary copy, then chunk2 maybe a Backup copy, and so on.

To me, it is more like refresh is just another merge.
so if you are not happy with the current merge, just move the code block from merge to refresh.

From Vault level, it doesn't matter whether it is mergable or refreshable or orderable,
just let vault know "is it expected the account will be accumulated ?"
if yes, it's upto vault decide how to accumulate
if not, remove refresh or merge traits from the API

**Comment by benjaminbollen** [comment]
> Vaults only get a single template type for the orderable account transfer that the Refresh message can carry in the group.  Every orderable record only carries a single value; and every refresh message only carries a single record.

This is up for discussion with vaults, but the Refresh message could look like 
struct Refresh<Value: Ord> {
  record_type_tag: u64,  // enumerates all possible databases in Vaults
  serialised_key: Vec<u8>,
  Value: Value 
}

The challenge I see is that Value needs to be the same type for all records. a u64 or f64; or we need to think of how routing can make multiple templated Value types that are orderable
arguably

**Comment by benjaminbollen** [comment]
> if yes, it's upto vault decide how to accumulate

this is the point, routing is not giving vault that choice.  Every record needs to hold an orderable value and Sentinel will resolve those orderable records on churn

**Comment by benjaminbollen** [comment]
The main reason for this is: on design of Sentinel it was explicitly chosen to not have a Sentinel with a mergeable trait for now, to ensure we get the security right.  There is instead an account sentinel that can resolve orderable records, but there is no (fourth) sentinel structure that can deal with a generic merge.  So all this is a consequence of the lingering merge trait in Sendable, and specific security choice in the lower layer (sentinel/routing).  Hope that helps understand why routing currently has little room to accomodate.
